language: java
jdk:
  - openjdk8
install: true
script:
  - "mvn clean install -Dgpg.skip=true"
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - "$HOME/.m2"

deploy:
  -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: target/bin/bintray.json
    user: kdyck
    key: $BINTRAY_API_KEY

